name: plex2jelly

services:
  plex2jelly:
    build: .
    restart: unless-stopped
    ports:
      - "8099:8099"
    environment:
      PLEX2JELLY_DB: /data/plex2jelly.db
    volumes:
      - /docker/plex4jelly/data:/data
      - /docker/plex4jelly/logs:/logs
